import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "png.pngtree.com",
      "example.com",
      "cdn.example.org",
      "static.vecteezy.com",
      "i2.wp.com",
      "images.contentstack.io",
      "ourlittlenook.com",
      "assets.rbl.ms",
      "media.istockphoto.com",
      "www.mybreadbakery.com",
      "cdn.centr.com",
      "jennifercooks.com",
      "www.kitchensanctuary.com",
      "sundaytable.co",
      "www.savingdessert.com",
      "www.allrecipes.com",
      "images.ctfassets.net",
      "www.inspiredtaste.net",
      "www.simplyrecipes.com",
      "leitesculinaria.com",
      "food.fnr.sndimg.com",
      "www.grocery.coop",
      "www.eatingwell.com",
      "media.cnn.com",
      "pbs.twimg.com",
      "dmd-mongolie.com",
      "correctmongolia.com",
      "i2.wp.com",
      "marcwiner.com",
      "static.vecteezy.com",
      "assets.rbl.ms",
      "farm6.static.flickr.com",
      "recipe30.com",
      "cdn.britannica.com",
      "littleferrarokitchen.com",
      "www.licious.in",
      "abajillianrecipes.com",
      "thesaltycooker.com",
      "www.rainbownourishments.com",
      "www.completementpoireau.ca",
      "static1.squarespace.com",
      "encrypted-tbn0.gstatic.com",
      "images.unsplash.com",
    ],
  },
  env: {
    API_URL: process.env.API_URL,
  },
};

export default nextConfig;
